name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Gp-Connect-Access-Record-Fhir-Build"
    trigger:
      branches:
        exclude:
          - master
          - refs/heads/master
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}   
    apigee_deployments:
      - environment: internal-dev
        jinja_templates:
          ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
          ENCRYPTED_VARIABLES_KVM_KEY_NHS_LOGIN_KEY: nhs_login_private_key
          GP_CONNECT_ENDPOINTS: gp-connect-access-record-endpoints-PR
        post_deploy:
          - template: ./templates/post-deploy.yml
      - environment: internal-dev-sandbox
        proxy_path: sandbox
        jinja_templates:
          ENCRYPTED_VARIABLES_KVM: just-dummy-value-for-suuccessfull-build
          ENCRYPTED_VARIABLES_KVM_KEY_NHS_LOGIN_KEY: just-dummy-value-for-suuccessfull-build
          GP_CONNECT_ENDPOINTS: just-dummy-value-for-suuccessfull-build
        post_deploy:
          - template: ./templates/post-deploy.yml
